### PR TITLE
Optimized order

### PR DESCRIPTION
**Pull request by kdiluca**
Please review the changes for optimized routing.  Keep in mind that the actual action name may change.  Also, I'm working on thor service tests so I don't want to merge the Optimized Order PRs until that is complete.  Thanks!

### CODE REVIEW

**Comment by kevinkreiser** [comment]
i would just use the matrix action to handle this, basically all the code is the same and you just to mess with the switch statement. just my opinion, less code duplication for the win

**Comment by kevinkreiser** [comment]
Code looks ok not sure why tests are failing maybe need to merge master into your branch?

**Comment by kevinkreiser** [comment]
Need to fetch merge origin/master to make build pass

**Comment by kdiluca** [comment]
strange...failing on baldr/tilehierarchy after I merged in origin/master

**Pull request closed without merging**
